### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vyaspranjal33**
added License badge

### CODE REVIEW

**Comment by eukreign** [comment]
GitHub already adds a license badge on the front page, do we need two on the same page?

image

**Comment by vyaspranjal33** [comment]
@eukreign  its good to have one badge Other lbry Projects already have it  

image

**Comment by eukreign** [comment]
Since GitHub already provides a license indicator/badge and you've agreed that one badge is enough I'm closing this PR. Please don't let this discourage you from making future PRs, we do merge most PRs.

**Comment by vyaspranjal33** [comment]
@eukreign other lbry projects are using both license badge as well as github indicator , i think this change should be accepted

**Pull request closed without merging**
