### PR TITLE
Add tests to travis

### PR DESCRIPTION
**Pull request by jobevers**
Adds a first pass at testing and linting to travis.

I'm ignoring the current tests right now, largely because they didn't work out of the box and I didn't want to spend much time messing around with them.  But, the framework is in place to start writing tests and having them run on each commit.

I also put in place some very liberally configured linting.  Hopefully, as code quality improves, the linting can become more strict.

### CODE REVIEW

**Comment by jobevers** [comment]
Should add that linting is currently failing - and the errors it is failing on look like they should be addressed or explicitly ignored.  I don't think that should be a blocker on merging this.

**Comment by jobevers** [comment]
In a chat with @lyoshenka decided that the errors are blockers.

**Comment by jobevers** [comment]
To help track, here are the current errors that pylint is reporting:

************* Module lbrynet.lbrynet_gui.StreamFrame
- [ ] E:121,12: self.cancel_func is not callable (not-callable)

************* Module lbrynet.lbrynet_gui.GuiApp
- [ ] E:207, 8: function already defined line 179 (function-redefined)

************* Module lbrynet.lbrynet_console.ControlHandlers
- [ ] E:123,15: self.control_handler_class is not callable (not-callable)

************* Module lbrynet.lbrynet_console.plugins.BlindRepeater.ValuableBlobQueryHandler
- [ ] E:104,16: Not enough arguments for logging format string (logging-too-few-args)
- [ ] E:196,20: Not enough arguments for logging format string (logging-too-few-args)

************* Module lbrynet.core.client.DownloadManager
- [ ] E: 55,16: Not enough arguments for logging format string (logging-too-few-args)

************* Module lbrynet.lbrylive.LBRYStdoutDownloader
- [ ] E: 25,23: Unexpected keyword argument 'dht_node_class' in constructor call (unexpected-keyword-arg)
- [ ] E: 25,23: Unexpected keyword argument 'stream_info_manager_class' in constructor call (unexpected-keyword-arg)
- [ ] E: 25,23: Unexpected keyword argument 'blob_manager_class' in constructor call (unexpected-keyword-arg)
- [ ] E: 25,23: No value for argument 'blob_data_payment_rate' in constructor call (no-value-for-parameter)
- [ ] E: 29,36: No value for argument 'blob_info_rate' in constructor call (no-value-for-parameter)
- [ ] E: 41,21: No value for argument 'wallet' in constructor call (no-value-for-parameter)
- [ ] E: 53,23: No value for argument 'upload_allowed' in constructor call (no-value-for-parameter)

************* Module lbrynet.lbrylive.LBRYStdinUploader
- [ ] E: 28,23: Unexpected keyword argument 'dht_node_class' in constructor call (unexpected-keyword-arg)
- [ ] E: 28,23: Unexpected keyword argument 'stream_info_manager_class' in constructor call (unexpected-keyword-arg)
- [ ] E: 28,23: Unexpected keyword argument 'blob_manager_class' in constructor call (unexpected-keyword-arg)
- [ ] E: 28,23: No value for argument 'blob_data_payment_rate' in constructor call (no-value-for-parameter)
- [ ] E: 33,36: No value for argument 'blob_info_rate' in constructor call (no-value-for-parameter)

**Comment by jobevers** [comment]
@lyoshenka @jackrobison 

This pull request should be good to go for a final review.  PTAL.

**Comment by lyoshenka** [comment]
I looked at the changes briefly. It's hard to tell what's what because Jack's updates are mixed in with the pylint stuff, so I'm leaving it to Jack for the final ok and the merge.

**Comment by jobevers** [comment]
@jackrobison I'd like to get this merged in so I can mentally unload this and move onto other things.  Is there anything you need from me?

**Pull request merged**
