### PR TITLE
emergency fix: force lbrycrd to be the default wallet

### PR DESCRIPTION
**Pull request by jobevers**
Ignore save settings for wallet type and use the default wallet (lbrycrd)
instead.  lbryum can be used but only if specified on the command line.

### CODE REVIEW

**Comment by lyoshenka** [comment]
looks good to me. ive been refactoring that file a bit and agree with the comments you made

**Comment by lyoshenka** [comment]
didnt test it though

**Comment by RdeWilde** [comment]
But would that mean wallet(file)s switch too? That would become a small disaster.

**Comment by jobevers** [comment]
@rdewilde - Its not great but one solution is to manually send coins from the lbryum wallet to the lbrycrd wallet.

**Pull request merged**
