### PR TITLE
html api doc generator

### PR DESCRIPTION
**Pull request by eukreign**

### CODE REVIEW

**Comment by tzarebczan** [comment]
@eukreign who needs to review this?

**Comment by eukreign** [comment]
I think @NetOperatorWibby is working on some CSS for this and will have a feedback for me on what else needs to be done.

**Comment by NetOperatorWibby** [comment]
Yup, massive changes are coming to .tech so this will have to wait a bit.

**Comment by wallermadev** [comment]
I have been keeping a eye on the design changes and too be honest I have
not been happy with most of them --

Can someone PLEASE get a designer who has their eyes open ... Who signed it
off.

Pissed --
Mathew Waller

**Pull request merged**
