### PR TITLE
Retry startup

### PR DESCRIPTION
**Pull request by jobevers**

### CODE REVIEW

**Comment by jobevers** [comment]
Jack commented that he's not sure some startup errors are recoverable in this way - like, if we've already started listening to 5279 it might fail on the second try while attempting to bind that port.

**Comment by jackrobison** [comment]
It's probably worth testing crashing startup throughout the stages - teardown might be necessary (port binding and opening the databases come to mind as potential problems).

**Comment by jobevers** [comment]
@jackrobison while there can be improvements to this that can be done, is there a reason not to merge it in?

**Comment by jackrobison** [comment]
@jobevers LGTM, go for it

**Pull request merged**
