### PR TITLE
Add 'application/x-lbry', '*.lbry' content type

### PR DESCRIPTION
**Pull request by skhameneh**
Required to make `lbry-format`, `lbry-unity`, and a new sandbox work.

## PR Checklist
Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [ ] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type
What kind of change does this PR introduce?

Why is this change necessary?

- [x] Bugfix
- [x] Feature
- [ ] Breaking changes (bugfix or feature that introduces breaking changes)
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number: N/A

### CODE REVIEW

**Comment by skhameneh** [comment]
This has been tested in `lbry-dektop` with a claim edit. 😃

**Comment by eukreign** [comment]
is this ready to be merged?

**Comment by tzarebczan** [comment]
I don't see why not :)

**Comment by eukreign** [comment]
Is there a proposal or some kind of write up related to this? It feels a little out of left field.

**Comment by jackrobison** [comment]
@skhameneh is this the media type? https://www.iana.org/assignments/media-types/application/vnd.unity

**Comment by tzarebczan** [comment]
Believe Shawn created a custom format that could be used in certain cases: https://github.com/lbryio/lbry-format 

There was some discussion as to whether or not this is the right way to go about this, but I'll let @skhameneh comment on that.

**Comment by skhameneh** [comment]
@jackrobison Tom is correct, this is a custom media type that follows `lbry-format` (Zstd > Tar, with package descriptor)

**Comment by skhameneh** [comment]
@eukreign this is ready to be merged, will not cause any forward-moving conflicts.

**Comment by eukreign** [comment]
replaced by https://github.com/lbryio/lbry/pull/1748

**Pull request closed without merging**
