### PR TITLE
[API] block get on bytes being written to the output file

### PR DESCRIPTION
**Pull request by jackrobison**

### CODE REVIEW

**Comment by tzarebczan** [comment]
Can this be extended to support https://github.com/lbryio/lbry/issues/1342 ? Is there any reason we wouldn't want to wait until the first blob is downloaded before the output file is written?

**Comment by tzarebczan** [comment]
Also, see https://github.com/lbryio/lbry/issues/854

**Comment by jackrobison** [comment]
@eukreign all that's left on this is updating `tests.unit.test_daemon.test_Downloader`

**Comment by eukreign** [comment]
what's the status of this? can it be merged or closed or what action can be taken on this?

**Comment by tzarebczan** [comment]
Tested this for Jack briefly and it works as expected.

**Pull request merged**
