### PR TITLE
Update various typos & edits

### PR DESCRIPTION
**Pull request by preserveddarnell**

### CODE REVIEW

**Comment by eukreign** [comment]
@preserveddarnell if you are still interested in getting this PR merged please make the minor changes requested.

**Comment by preserveddarnell** [comment]
> @preserveddarnell if you are still interested in getting this PR merged please make the minor changes requested.

Fixed

**Comment by eukreign** [comment]
@preserveddarnell Can you also drop the changes to the CHANGELOG, I don't think capitalizing the first word in every bullet is necessary.

**Comment by preserveddarnell** [comment]
> @preserveddarnell I would like to merge your changes to `INSTALL.md` and `README.md`, can you please drop the others and rebase against latest master? Once you do that I promise I won't have any more requests :-) and will merge!

I think my changes are valid and would be supported by others. I will leave it as-is.

**Comment by eukreign** [comment]
Manually merged https://github.com/lbryio/lbry/commit/aed00b53fdf637f72fdb855a3821b3c1970f0c15

**Pull request closed without merging**
