### PR TITLE
Daemon connects even if port 3333 is bound.

### PR DESCRIPTION
**Pull request by hackrush01**
Daemon incrementally searches for open ports until it is found(queries
10 ports ahead of peer_port).
Then informs the user of the port that is used.

Fixex #710

### CODE REVIEW

**Comment by kaykurokawa** [comment]
Don't think we can merge this. My response on  #710:

Ports to bind to should never automatically change to some other random port. This is poor practice because people need to write firewall rules which requires fixed port numbers. It also makes testing the service on the port impossible because it could be bound to some random port that the client has no knowledge of.

It definitely should give proper feedback if it failed to bind to a port, and probably include instructions on how to change the port through the config file.

**Comment by hackrush01** [comment]
That could also be taken care of. Should I instead print out instructions do change the port?

**Comment by hackrush01** [comment]
@kauffj @zestyr @jackrobison 
This PR builds on the PR by @zestyr and adds support for downloading from http and bittorent sources. It has some callbacks that need fixing, otherwise it is working. The lbryschema has to be updated and libtorrent has to be installed inside the python virtual env which is bit of a tough nut to crack.

**Comment by lyoshenka** [comment]
This feels like two separate PRs. Can you break this up please?

**Comment by hackrush01** [comment]
Done.

**Comment by kauffj** [comment]
@hackrush01 rather than change the port, please update this to fail to start and ensure that the info returned by `status` indicates the reason why.

**Comment by lyoshenka** [comment]
This is good, but linking people to lbry.io/faq is not ideal. Can you write a faq article to link people to? See https://github.com/lbryio/lbry.io/blob/master/content/faq/how-to-stop-lbry.md as an example of a file that gets transformed into a faq article.

**Comment by hackrush01** [comment]
Yes, I will do that in a short while.

**Pull request merged**
