### PR TITLE
Add traceback to error in EncryptedFileManager

### LINKED ISSUE #478: File Manager error
Seeing lots of errors:
`An error occurred while starting a lbry file: 'NoneType' object has no attribute '__getitem__'`

Logged in EncryptedFileManager:89

### PR DESCRIPTION
**Pull request by jobevers**
Doesn't fix #478, but will help with diagnosing it.

### CODE REVIEW

**Comment by kaykurokawa** [comment]
LGTM

**Comment by jobevers** [comment]
@kaykurokawa I had to make some fixes/changes after rebasing, can you take a second look at this?

**Comment by kaykurokawa** [comment]
I think these returnValue's don't seem necessary? 

https://github.com/lbryio/lbry/blob/520ac9b50aced69063eae6580ac8840971c4a75b/lbrynet/lbryfilemanager/EncryptedFileDownloader.py#L67

https://github.com/lbryio/lbry/blob/520ac9b50aced69063eae6580ac8840971c4a75b/lbrynet/lbryfilemanager/EncryptedFileDownloader.py#L70

otherwise LGTM

**Comment by jobevers** [comment]
Those were added here: https://github.com/lbryio/lbry/commit/8de6bd7c7a2fecc4d786f70b28ccb8d870d5c41d and are just part of the rebase. 

Taking them out could be part of a new PR.  I'll take a look.

**Pull request merged**
