### PR TITLE
explicitly list jsonrpc params in function signature. add jsonrpc tests

### PR DESCRIPTION
**Pull request by lyoshenka**

### CODE REVIEW

**Comment by lyoshenka** [comment]
not sure if i wrote the tests correctly. i dont really understand how testing and async go together

**Comment by jobevers** [comment]
I'm going to rebase this and force push to see if it fixes the build

**Comment by jobevers** [comment]
The tests are good.  One of the points of `trial` is that it takes care of making sure the deferreds run on each test.

**Comment by lyoshenka** [comment]
im going to take this to mean you approve the PR

**Pull request merged**
