### PR TITLE
update index.md

### PR DESCRIPTION
**Pull request by ykris45**
fixed slack to discord

### CODE REVIEW

**Comment by MSFTserver** [comment]
daemon.py isnt complete

**Comment by ykris45** [comment]
Please Review my PR and if this PR accepted , fix url webhook of LBRY Discord server. im sure its diferent with slack webhook.

**Comment by lyoshenka** [comment]
@ykris45 we still use slack for internal communication, and that's where these bug reports go. so slack is correct here.

**Comment by ykris45** [comment]
im understand now sir. thanks very much

**Pull request closed without merging**
