### PR TITLE
Fix broken dependencies on Arch.

### PR DESCRIPTION
**Pull request by wolf9466**

### CODE REVIEW

**Comment by jobevers** [comment]
Unfortunately, unqlite is a pain and we've had difficulty getting other versions to work on ubuntu.  In the near future we're simply going to remove it as its being used for very little.

**Comment by wolf9466** [comment]
How about a >= on unqlite?

**Comment by jackrobison** [comment]
@wolf9466 

https://github.com/lbryio/lbry/pull/348

**Comment by jobevers** [comment]
Closing this in favor of https://github.com/lbryio/lbry/pull/353 and https://github.com/lbryio/lbry/pull/348

**Pull request closed without merging**
