### PR TITLE
Filemanager related unit tests

### PR DESCRIPTION
**Pull request by kaykurokawa**
Just some unit tests for file manager related classes. 

Added random_lbry_hash() function to generate random lbry hases in tests.util 

Add tests for EncryptedFileSaver and DBEncryptedFileMetadataManager (aka stream_info_manager).

### CODE REVIEW

**Comment by kaykurokawa** [comment]
Will add some tests for EncryptedFileManager class

**Comment by kaykurokawa** [comment]
Added test for EncryptedFileManager class, rebased to single commit

**Comment by jackrobison** [comment]
LGTM

**Comment by kaykurokawa** [comment]
I'll merge this in conjunction with jack's filemanager refactor

**Comment by kaykurokawa** [comment]
changed it so that it will make database in a temporary folder and properly tear itself down. rebased.

**Pull request merged**
