### PR TITLE
Docs spelling correction.

### PR DESCRIPTION
**Pull request by mikeputnam**

### CODE REVIEW

**Comment by kauffj** [comment]
Thanks @mikeputnam!

@lyoshenka @jackrobison shouldn't the docs not be checked into the repo and instead auto-generated?

**Comment by lyoshenka** [comment]
That's correct

**Comment by tzarebczan** [comment]
@lyoshenka same for https://github.com/lbryio/lbry/pull/875 I guess.

**Comment by lyoshenka** [comment]
We're gonna try to move https://github.com/lbryio/lbry/issues/762 to the top of the list, so this is automated in the future.

**Pull request merged**
