### PR TITLE
Increased max_key_fee

### LINKED ISSUE #721: Re-think max_key_fee
There's a `max_key_fee` config in the daemon that prevents you from downloading anything over that fee. It's set to 25 USD by default. I think this needs to be changed somehow.

Option 1: remove it completely. the app already confirms before spending

Option 2: remove the default, or set it very high. Then if you want to actually enforce a limit, you can set it yourself.

Option 3: leave it as is

I'd prefer option 2.

Related app issue: https://github.com/lbryio/lbry-app/issues/268

### PR DESCRIPTION
**Pull request by hackrush01**
The default max_key_fee value is increased to US$ 50.
Fixes #721

### CODE REVIEW

**Comment by jackrobison** [comment]
LGTM

**Comment by hackrush01** [comment]
LGTM means?

**Comment by jackrobison** [comment]
@hackrush01 Looks good to me

**Comment by hackrush01** [comment]
Oh OK Thanks!

**Pull request merged**
