### PR TITLE
[WIP] Remove twisted dependency from reflector package

### PR DESCRIPTION
**Pull request by binaryflesh**
## PR Checklist
Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [ ] I have checked that this PR does not introduce a breaking change
- [x] This PR introduces breaking changes and I have provided a detailed explanation below
WIP pull request. This will be unchecked when review is requested. I will have to re-write tests and make sure code utilizing `asyncio` interacts with existing code written with `twisted` works as intended.

## PR Type
What kind of change does this PR introduce?
Removes an external third-party dependency from `lbrynet`. Replaces `twisted` with library supported by python project. Reflector is very dependent on `twisted.internet.Protocol` and `twisted.internet.Client/ServerFactory`. `asyncio` does not have this functionality out-of-the-box, so there is a bit of exploratory code in this PR. I will not be using `BufferedProtocol` despite being the closest thing to the original code utilizing `twisted`, given this comment in the source: [Important: this has been added to `asyncio` in Python 3.7 *on a provisional basis*!  Consider it as an experimental API that might be changed or removed in Python 3.8.](https://docs.python.org/3/library/asyncio-protocol.html#buffered-streaming-protocols). I am trying to avoid unix pipes, posix signals, `subprocess`, and proactor loops (OS compatibility), but will document reasoning if this happens to be a roadblock.

Why is this change necessary?
Future-proof lbrynet components, have fewer run-time dependencies, and be platform neutral.

- [ ] Bugfix
- [ ] Feature
- [ ] Breaking changes (bugfix or feature that introduces breaking changes)
- [x] Code style update (formatting)
- [x] Refactoring (no functional changes)
- [ ] Documentation changes
- [x] Other - Please describe: I have made a few slight modifications to reflector's package structure that feel appropriate given majority of the component must be re-written from scratch.

## Fixes

Issue Number: N/A

## Other information

As of now, this PR is not ready for unit testing. I am taking a test-driven approach given I must rewrite the previous unit test. This PR is a full rewrite of the component. Level of effort is estimated for about a week, week and a half, to have running smoothly.

### CODE REVIEW

**Comment by tzarebczan** [comment]
Hey @binaryflesh, thanks for starting up this PR!! Please let us know if you have any questions. 

Once it's all done, can we [show you some appreciation](https://lbry.io/faq/appreciation)?

**Comment by eukreign** [comment]
@binaryflesh before you get too far more into this, keep in mind that the branch where the blob stuff and DHT has been completely rewritten to be asyncio is in https://github.com/lbryio/lbry/pull/1704 I would highly recommend rebasing against that instead of master.

**Comment by eukreign** [comment]
We are looking to switch from using TCP for client<->daemon communication to using unix domain sockets, windows named pipes and Service Message passing on Android. You mentioned something about not using unix sockets in your PR description, can you elaborate on downside of using unix domain sockets?

**Comment by binaryflesh** [comment]
Thanks for the heads up. Regarding unix sockets/ posix signals, no technical reason. I was just trying to stick cross-platform until issue arose. Regarding pieces like `FileSender` and `Producer` in reflector/client for example using unix sockets is probably the best way to go.

**Comment by binaryflesh** [comment]
@eukreign @jackrobison regarding daemon; do I still need to support all three calls (file reflect, blobs, all blobs) that are roughly about here: [code using reflector](https://github.com/lbryio/lbry/blob/master/lbrynet/extras/daemon/Daemon.py#L3242)

**Comment by jackrobison** [comment]
https://github.com/lbryio/lbry/pull/1810 adds basic reflect-after-publish

For known remaining reflector issues there are https://github.com/lbryio/lbry/issues/1811 and https://github.com/lbryio/lbry/issues/1812 - can you open a new PR for one/both of these?

**Pull request closed without merging**
