### PR TITLE
Query available blobs and Upload to Lighthouse Scripts

### PR DESCRIPTION
**Pull request by jobevers**
The output of this script is actually repeatable now.  I was running into locking issues with sqlite so I made a new storage class for the nameclaim metadata.

This is a WIP because I still need to incorporate the wallet changes into the rest of lbrynet.

### CODE REVIEW

**Comment by jobevers** [comment]
I'm still making progress on this... slowly.

**Comment by jobevers** [comment]
Pulled out just the wallet metadata stuff: https://github.com/lbryio/lbry/pull/363

**Comment by jobevers** [comment]
still working on this..

**Comment by jobevers** [comment]
Note that this includes the changes in here: https://github.com/lbryio/lbry/pull/388, but I thought that was worth its own PR.

**Comment by jackrobison** [comment]
👍

**Pull request merged**
