### PR TITLE
upgrade twisted to 16.6

### PR DESCRIPTION
**Pull request by jobevers**

### CODE REVIEW

**Comment by jackrobison** [comment]
not forgetting about this, but I'd like to hold off until simplification of requirements.txt is on master, unless it's specifically needed already.

**Comment by jobevers** [comment]
sounds good; I'll reassign this back to me until its more appropriate

**Comment by jobevers** [comment]
Yep, I'm still aware this is here

**Comment by jobevers** [comment]
I'm going to close this until post-electron changes, as electron simplifies the build process for lbrynet.

**Pull request closed without merging**
