### PR TITLE
set build type in travis

### PR DESCRIPTION
**Pull request by lyoshenka**
Travis built this successfully, but I don't think that I can test whether it worked or not without getting the finished .deb. Can you please merge this before the nightlys get built? I'll check this first thing tomorrow morning and revert it if anything's broken.

### CODE REVIEW

**Comment by lyoshenka** [comment]
fixed

**Comment by jobevers** [comment]
LGTM

**Comment by jobevers** [comment]
Oh, right, damn:  GNU sed and BSD sed are different.  BSD sed doesn't like an empty `-i` flag.

**Comment by lyoshenka** [comment]
:unamused:

**Pull request merged**
